# IoT Edge CI Build Definition
# Build your IoT Edge Modules in VSTS
# https://aka.ms/yaml

queue:
  name: Hosted Linux Preview

steps:
  - task: CopyFiles@2

    displayName: "Copy unaltered source to: $(Build.ArtifactStagingDirectory)"

    inputs:
      SourceFolder: "$(Build.SourcesDirectory)"
      Contents: "/**/*.*"
      TargetFolder: "$(Build.ArtifactStagingDirectory)"

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3

    displayName: "Replace tokens in deployment.template.json"

    inputs:
      rootDirectory: EdgeSolution
      targetFiles: deployment.template.json

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3

    displayName: "Replace tokens in modules/**/module.json"

    inputs:
      rootDirectory: EdgeSolution

      targetFiles: "modules/**/module.json"

  - task: vsc-iot.iot-edge-build-deploy.custom-build-release-task.edge-cicd-task@1

    displayName: "Azure IoT Edge - Build modules"

    inputs:
      action: "Build modules"

      moduleJsons: "modules/**/module.json"

      rootPath: EdgeSolution

  - task: PublishBuildArtifacts@1

    displayName: "Publish Artifact: drop"